[package]
name = "todo_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = {versione = "1.0", deafult-feature = false, features = ["alloc"]}