version: "3.3"
services:
    postgres:
      container_name: 'to-do-postgres'
      image: 'postgres:14.4'
      restart: always
      ports:
        - '5432:5432'
      environment:
        - 'POSTGRES_USER=username'
        - 'POSTGRES_DB=to_do'
        - 'POSTGRES_PASSWORD=password'